language: cpp
script: true
compiler:
  - clang
  - gcc
notifications:
  slack: 3307-orange:YAFPqWGvHpDpBOhLeq5D5wO6
addons:
  apt:
    packages:
      - libboost-all-dev
      - qt5-default
      - gcc-5
      - clang-3.7
    sources:
      - ubuntu-sdk-team
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7